set(DEPS)
set(CLIENTDEPS)
set(BUILDCLIENT TRUE)
set(BUILD TRUE)

macro(DEP VAR NICK)
    if( NOT ${VAR}_FOUND )
        message( SEND_ERROR "${NICK} is required to build ${progtitle}" )
        set(BUILD FALSE)
    endif()
endmacro(DEP)

macro(CLIENTDEP VAR NICK)
    if ( NOT DEDICATEDONLY )
        if( NOT ${VAR}_FOUND )
            message( "${NICK} is required to build a ${progtitle} client" )
            set(BUILDCLIENT FALSE)
        endif()
    endif()
endmacro(CLIENTDEP)
