# conanoptions.ini for ArmagetronAd
[options]
sdl2/*:shared=True
libxml2/*:html=False
libxml2/*:http=False
libxml2/*:ftp=False
libxml2/*:zlib=False
libxml2/*:iconv=False
sdl/*:directx=False
sdl/*:x11=False
sdl/*:xvm=False
sdl/*:xcb=False
sdl/*:vulkan=False
sdl/*:opengles=False
sdl/*:libunwind=False
sdl/*:hidapi=False
sdl/*:xshape=False
sdl/*:xcursor=False
sdl/*:xinput=False
sdl/*:xrandr=False
sdl/*:xinerama=False
libcurl/*:with_ssl=False
libcurl/*:with_https=False
libcurl/*:with_ftp=False
libcurl/*:with_file=False
libcurl/*:with_rtsp=False
libcurl/*:with_dict=False
libcurl/*:with_telnet=False
libcurl/*:with_tftp=False
libcurl/*:with_pop3=False
libcurl/*:with_imap=False
libcurl/*:with_smtp=False
libcurl/*:with_gopher=False
libcurl/*:static=False
*/*:flac=False
*/*:shared=True
