#!/usr/bin/env python

import sys
import subprocess

def find_version(version, should_generalize=True):
    """Returns a normalized OS X version string.
    
    >>> find_version("10.8")
    '10.8.0'
    >>> find_version("10.8.2")
    '10.8.0'
    >>> find_version("10.3.9", False)
    '10.3.9'
    """
    parts = version.split(".")
    major = parts[0]
    minor = parts[1]
    bug   = "0"
    if not should_generalize and len(parts) == 3:
        bug = parts[2]
    return ".".join([major, minor, bug])

if __name__ == '__main__':
    if len(sys.argv) == 2:
        print find_version(sys.argv[1], False)
    else:
        print find_version(subprocess.check_output(["sw_vers", "-productVersion"]).strip(), True)
