macro(GetDLLs out)
    if(WIN32)
        foreach(lib ${ARGN})
            if(${lib} MATCHES ".*;.*")
                foreach(lib_ ${lib})
                    GetDLL(${out} ${lib_})
                endforeach()
            else()
                GetDLL(${out} ${lib})
            endif()
        endforeach()
    endif()
endmacro()

macro(GetDLL out lib)
    if(${lib} MATCHES ".*/.*")
        if(${lib} MATCHES ".*.dll$")
            DLLs_list_append_once(${out} ${lib})
            CheckDLLDeps(${out} ${lib})
        else()
            file(STRINGS ${lib} dllnames
                 REGEX "^.*\\.dll$")
            foreach(dllname ${dllnames})
                find_file(${dllname}_PATH ${dllname})
                DLLs_list_append_once(${out} ${${dllname}_PATH})
                CheckDLLDeps(${out} ${${dllname}_PATH})
            endforeach()
        endif()
    endif()
endmacro()

macro(CheckDLLDeps out dll)
    file(STRINGS ${dll} dllnames
            REGEX "^.*\\.dll$")
    foreach(dllname ${dllnames})
        string(TOLOWER ${dllname} dllname_)
        if(NOT ${dllname_} MATCHES "^(lib)?(kernel|ms.*|user|gcj_s|gdi)(32|64)?(\\.dll)?$")
            find_file(${dllname}_PATH ${dllname})
            DLLs_list_append_once(${out} ${${dllname}_PATH})
            if(NOT ${${dllname}_PATH} STREQUAL ${dll})
                CheckDLLDeps(${out} ${${dllname}_PATH})
            endif()
        endif()
    endforeach()
endmacro()

macro(DLLs_list_append_once list item)
    list(FIND ${list} ${item} found)
    if(${found} LESS 0)
        list(APPEND ${list} ${item})
    endif()
endmacro()
