LABEL maintainer="Manuel Moos <z-man@users.sf.net>"

USER root

# more build dependencies
RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get install \
curl \
git \
make \
rsync \
gpg \
-y

#USER steam
